<a href="https://colab.research.google.com/github/elavens/PyMe/blob/main/PCA_EigenValues_and_EigenVectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np
# Define a 3x3 matrix
matrix = np.array([[2, 1, 3],
                   [4, 5, 6],
                   [9, 8, 7]])

In [38]:
# Find the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
# Print the eigenvalues
print("Eigenvalues:")
for eigenvalue in eigenvalues:
    print(eigenvalue)

# Print the eigenvectors
print("\nEigenvectors:")
for i in range(len(eigenvectors)):
    print("Eigenvector", i+1)
    print(eigenvectors[:, i])
    print()

Eigenvalues:
15.150201023986735
1.1292949431462855
-2.2794959671330135

Eigenvectors:
Eigenvector 1
[-0.22452506 -0.55992487 -0.79754162]

Eigenvector 2
[-0.6362489   0.76817312 -0.07139599]

Eigenvector 3
[-0.46202087 -0.3989679   0.79206145]

